### ISSUE TITLE
Allmän tracker för saker som kommer kunna behöva ändras i adminsystemet

### ISSUE THREAD

**Issue by drakejacob** [cthit/nollk.it#7]
- [ ] Favicon
- [ ] 'title' för varje delsida
- [ ] Managea moduler
- [ ] Ändra schemat/kalendern
- [ ] Uppdatera bilder i sittande NollKIT för "Vi är NollKIT"
- [ ] Text för varje person på "Vi är NollKIT"
- [ ] Generell text typ överallt
- [ ] Bakgrundsbilden
- [ ] Märket i headern
- [ ] Göra så att man kan sätta tema-fonten (göra så att man ändra från Passion One)
- [ ] Sätta startdatum för mottagingen
- [ ] Länkar till kalendrar för introkurser och mottagningen (dessa kalendrar måste vara publika, inför en check för detta redan i adminsystemet!)

**Comment by daancs** [comment]
Är detta klart? @MechaFlex
